ad = input('Digite o der na sua cabeça: ')
print(' é alfanumerico? ',ad.isalnum())
print(' é texto?' ,ad.isalpha())
print(' é decimal?' ,ad.isdecimal())
print(' é identificador? ',ad.isidentifier())
print(' é titulo?' ,ad.istitle())
print(' é com letras minuscula?',ad.islower())
print(' contem espaços?' ,ad.isspace())
print(' é com letras maiusculas?' ,ad.isupper())