num = int(input('Um numero para tabuada dele mesmo: '))
print('{} x {:2} = {}'.format(num,1,num*1))
print('{} x {:2} = {}'.format(num, 2, num*2))
print('{} x {:2} = {}'.format(num, 3, num*3))
print('{} x {:2} = {}'.format(num,4, num*4))
